#!/bin/bash

if ! command -v xclip &> /dev/null
then
    sudo apt-get install -y xclip
fi

read -s -p "Enter your password: " password
echo

read -s -p "Enter the salt: " salt

hashed_password=$(echo -n "$password" | sha256sum | awk '{print $1}')

final_hash=$(echo -n "$hashed_password$salt" | sha256sum | awk '{print $1}')

if [[ ${final_hash:0:10} == "ea4978a7e4" && ${final_hash: -10} == "65e3d2337a" ]]; then
    echo -n "$final_hash" | xclip -selection clipboard
    echo -e "\n Hash copied to clipboard!"
else
    echo -e "\n Wrong hash"
fi
